version: 0.2

phases:
  install:
    commands:
      - npm ci
  build:
    commands:
      - npm run webpack:build --tags=smoke
      - export SPRYKER_TEST_TYPE=smoke
      - npm run docker:up
      - npm run docker:run
artifacts:
  files:
    - '**/*'
