name: CI

# This workflow is triggered on pushes and pull requests to the repository.
on: [pull_request]

jobs:
  code-quality-check:
    name: Check Code Quality (Prettier & ESLint)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Check Prettier Formatting
        run: npm run prettier:check

      - name: Run ESLint
        run: npx eslint ./src
